# Hydra configuration for finetuning on the Scared1-1 dataset

# --- Model anad Checkpoint Configuration ---
model: "ARCroco3DStereo(ARCroco3DStereoConfig(state_size=768, state_pe='2d', pos_embed='RoPE100', rgb_head=True, pose_head=True,  img_size=(224, 224), head_type='linear', output_mode='pts3d+pose', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), pose_mode=('exp', -inf, inf), enc_embed_dim=1024, enc_depth=24, enc_num_heads=16, dec_embed_dim=768, dec_depth=12, dec_num_heads=12))"
# IMPORTANT: Replace this with the actual path to your pretrained model
pretrained: "/hy-tmp/CUT3R/src/cut3r_512_dpt_4_64.pth" 
load_only_encoder: False
long_context: False
fixed_length: True
resume: null
benchmark: True
num_views: 4
num_test_views: 4
n_corres_train: 0
n_corres_test: 0

# --- Loss Configuration ---
train_criterion: ConfLoss(Regr3DPose(L21, norm_mode='?avg_dis'), alpha=0.1) + RGBLoss(MSE)
test_criterion: Regr3DPose(L21, norm_mode='?avg_dis', gt_scale=True, sky_loss_value=0) + Regr3DPose_ScaleInv(L21, norm_mode='?avg_dis', gt_scale=True, sky_loss_value=0) + RGBLoss(L21)

# --- Dataset Configuration ---
# We only need to define our new dataset
train_dataset_def: Scared_Multi(ROOT='/hy-tmp/CUT3R/scared_processed', aug_crop=16, resolution=224, transform=SeqColorJitter, num_views=${num_views}, n_corres=${n_corres_train})
train_dataset: 20 @ ${train_dataset_def} # Use the full training dataset for each epoch

# Use the full validation set
test_dataset_def: Scared_Multi(ROOT='/hy-tmp/CUT3R/scared_validation_processed', resolution=224, num_views=${num_test_views}, seed=42, n_corres=${n_corres_test})
test_dataset: 20 @ ${test_dataset_def}

# --- Training Parameters for Finetuning ---
seed: 42
batch_size: 20 # Maximizing 32GB V100 utilization
accum_iter: 2 # Gradient accumulation
gradient_checkpointing: True
epochs: 20 # Reduced from 100 for finetuning
start_epoch: 0
weight_decay: 0.05
lr: 2e-5 # Increased for adapting to a new domain (medical data)
min_lr: 1e-6
warmup_epochs: 2 # Reduced from 10
amp: 0

# --- General Configuration ---
num_workers: 8
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

# --- Logging and Saving ---
eval_freq: 1
save_freq: 1000 # Set to a very large number to disable periodic saving
keep_freq: 5
print_freq: 10
print_img_freq: 100
num_imgs_vis: 4
save_dir: 'checkpoints'
exp_name: 'scared_full_finetuneV2' # A new experiment name
task: 'cut3r'
logdir: ./${save_dir}/${exp_name}/logs
output_dir: ./${save_dir}/${exp_name}/
hydra:
  verbose: True
  run:
    dir: ./${save_dir}/${exp_name} 